apiVersion: v1
clusters:
- cluster:
    server: https://gameserverclusterprod-dns-o0owfoer.hcp.eastus.azmk8s.io:443
  name: GameServerClusterProd
contexts:
- context:
    cluster: GameServerClusterProd
    user: clusterUser
  name: GameServerClusterProd
current-context: GameServerClusterProd
kind: Config
preferences: {}
users:
- name: clusterUser
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: /usr/local/bin/kubelogin
      args:
        - get-token
        - --environment
        - AzurePublicCloud
        - --server-id
        - 6dae42f8-4368-4678-94ff-3960e28e3630
        - --client-id
        - 80faf920-1908-4b52-b5ef-a8e7bedfc67a
        - --tenant-id
        - ad4ae26b-3f21-4c3f-82bc-d2d56886c5e3
        - --login
        - msi