apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQXRHZ0F3SUJBZ0lSQUt0enVlZlJTTGZ0aWhRSS9DN21FYjR3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdJQmNOTWpReE1UQTNNVGd3TnpVNVdoZ1BNakExTkRFeE1EY3hPREUzTlRsYQpNQTB4Q3pBSkJnTlZCQU1UQW1OaE1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBCnZpL1dvMkx4bm9ZckoxM05ub29tZnVid0JMK1g0YlpkRmljVE91Y25oNjlZaW8xeGJhQjU3SzhVYzRBTUNTdHEKS2U5SzVLRUJWZG15ZTRIL1FhWTdvTUtMMmNIQkovVUdkQS91bm80d0dvOFN3bXZYOHJwd3JNRysxNWxvSyt5egpjcjJZeVNGTnJWL2hDSTdETHZsRlcySFpkZWRwRmZVSVBENDErT3pKMDRIM2hvdFZvNzNFR05TMlYyczdMTEVjCkhKcmZZcGlyOE9PWE1pNGNHUVNoUGx2R3I4OGNkVHg3R1Z3YW1tbzB0M1YxZ3lzMWU5MEVYdDdtekNTS1poRDIKWWVnaThJc3RkS2FpN29KdUpJZzZxQVRDWnllVjA1RC9Bb0hvanVEUnN2SDkxaHRlV082c0dlR0h4RjVTNldxawpvZGdIblBWSUMxMEl1NExhV2hUNjVYSWVlaWNzWlFNNVFyOGNxNzZiTmpBbkR5V0gwT0QrUUVUZHFheUdpMXRJCk4wMGM2RTRPNkNmejNScjZJS2tYTGMrNWlHRGcyRm1XRFFDRUpwZWhMTTRTL1hacklCZkFyR2ZSNndIdmVKWEsKQUk2bTJkMTdpRHRhSDI2N0s2VjVMSkZYdVFlbkY3eFAyOEMwN3RyZ0t0OFN2WDZzb3MxV3ZNTGFDdGRjOHJONwpBeUpWZHkyL2pWdUM3RUFvRVZMekVOT0JxaGFCZncrOEN6Yzd5cExWUktac2p3WEpVZ28vVSt0Y241SUtGNS96Cm05ZVdJTXRUMzVudWtseXgyQ0F0cmdUeU5HZXJkeG1CTk5RSlRMdUhpMlIxZ3FFSUVvcjJXTlhjQ1NseUFBYlAKNmcrSmpiYnJDc0ZaeHlwaXNKYW1wMmt2cG9KeEJzWUdTUGY4ZGJnSk9iY0NBd0VBQWFOQ01FQXdEZ1lEVlIwUApBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTXpSTlpBVWRoMWJqc2ZpCklyVmNQdnFEajZMaU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQnp3MzRkV0JpSjdneTVVOXVPZjhSQ0lxdWUKd2ZkckUydTg5bEdPZHNxRzU4Vm96aUZyZ1hoVG5nc1hNeWlDNnlzSVRFSDM5ZXZvaE5XYUw4UjU3T1FNaWhIVAptS0wwZ2lGYzlFSW9mZDN2Y3JXV0JnTXRYRU00S1ZsOUFHZDdvZWpFYWVaTC9GN1JuWDNBbVQ5cVJnQUxIOGJHCktaWjhNeVZneXdPVkVWNk5wL0t0Wm5wcXlVdi9lcHlEY1NZT1lJcW1QUjBnV0dvQ0ZFR01tR0p2bk56ZE9pVGcKMTlPQ0M3UHJ5NzdPM2tuU1hwb1YrNXMyRHdkUHN0Zy85ZFdjK0NPSWpNZjZ3V3N2SWI4d053K1dNaWJMVUNBcQpIRTZHdW8yalA5bXkwRU1IK1JsdVBuVjJndmtXblFkR2hXM09pSGV5M1pvQ1VKbUdiS3NIR0w3S25MV1pTdDVrCk5pNEdsaG1ibDNUMXZKUmZPY3NsR0RTQ0lTZWozZ2gwaHBVV1Z5Mkp2S0hnMjdBUGFvMS9obEhLSWxsL01KMCsKa3o5MmJYRkJPRGgrQXJRRHV1VURYMS9zQ1dMRG1SYjNqMHJpeVQ4aGtUS09MMVNDekJ5T2xSTUNFUFFzY2lpVgpkbE9YZU9ROVd3QjVibmp3aU1nbEdReC8waHMzTFd2RlJyd25La1UwMDJTMlJxcXJTTXRLUWdPaWFhM0cxNGxvCjUvUzRCbU5vYnp1NTVKMDFuRlpmbHNZN2Vzc0RsUkdoVnhibGxEcHZFaUhqVE1RNmlWOGc4NGlUam1FbzJ3c2oKQlpqZTNzS0taVU9TYVoxVlFsYkZLOU9YMHgrNGpFSXNmWGdvNVcwcTJWbHF0Z1pvc0JQMXFEU1dBbEV3UFhMMAo0dXIzK0drTEpEYWFXTEVqWGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://gameserverclusterprod-dns-o0owfoer.hcp.eastus.azmk8s.io:443
  name: GameServerClusterProd
contexts:
- context:
    cluster: GameServerClusterProd
    user: clusterUser_GameServerRG_GameServerClusterProd
  name: GameServerClusterProd
current-context: GameServerClusterProd
kind: Config
preferences: {}
users:
- name: clusterUser_GameServerRG_GameServerClusterProd
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - devicecode
      - --server-id
      - 6dae42f8-4368-4678-94ff-3960e28e3630
      - --client-id
      - 80faf920-1908-4b52-b5ef-a8e7bedfc67a
      - --tenant-id
      - ad4ae26b-3f21-4c3f-82bc-d2d56886c5e3
      - --environment
      - AzurePublicCloud
      command: kubelogin 